import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { aiRateLimit } from "../middleware/rateLimit.js";
import { aiRoutes } from "./aiRoutes.js";
import { analyticsRoutes } from "./analyticsRoutes.js";
import { activityRoutes } from "./activityRoutes.js";
import { auditRoutes } from "./auditRoutes.js";
import { auditLogRoutes } from "./auditLogRoutes.js";
import { authRoutes } from "./authRoutes.js";
import { billingRoutes } from "./billingRoutes.js";
import { contactRoutes } from "./contactRoutes.js";
import { onboardingRoutes } from "./onboardingRoutes.js";
import { profileRoutes } from "./profileRoutes.js";
import { renewalRoutes } from "./renewalRoutes.js";
import { reportRoutes } from "./reportRoutes.js";
import { savingsRoutes } from "./savingsRoutes.js";
import { subscriptionRoutes } from "./subscriptionRoutes.js";
import { teamRoutes } from "./teamRoutes.js";
import { vendorRoutes } from "./vendorRoutes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/analytics", analyticsRoutes);
apiRouter.use("/activity", requireAuth, activityRoutes);
apiRouter.use("/contact", contactRoutes);
apiRouter.use("/onboarding", requireAuth, onboardingRoutes);
apiRouter.use("/profile", requireAuth, profileRoutes);
apiRouter.use("/billing", requireAuth, billingRoutes);
apiRouter.use("/vendors", requireAuth, vendorRoutes);
apiRouter.use("/subscriptions", requireAuth, subscriptionRoutes);
apiRouter.use("/team", requireAuth, teamRoutes);
apiRouter.use("/audit", requireAuth, auditRoutes);
apiRouter.use("/audit-logs", requireAuth, auditLogRoutes);
apiRouter.use("/renewals", requireAuth, renewalRoutes);
apiRouter.use("/reports", requireAuth, reportRoutes);
apiRouter.use("/savings", requireAuth, savingsRoutes);
apiRouter.use("/ai", requireAuth, aiRateLimit, aiRoutes);
