import { Vendor } from "../models/Vendor.js";
import { classifyVendorWaste } from "./wasteDetection.js";

const DAY_MS = 24 * 60 * 60 * 1000;

export async function seedSampleVendors(companyId) {
  const existingSampleCount = await Vendor.countDocuments({ company: companyId, source: "sample" });
  if (existingSampleCount > 0) return;

  const vendors = buildSampleVendors(companyId).map((vendor) => ({
    ...vendor,
    ...classifyVendorWaste(vendor),
  }));

  await Vendor.insertMany(vendors, { ordered: false });
}

function buildSampleVendors(companyId) {
  const daysAgo = (days: number) => new Date(Date.now() - days * DAY_MS);
  const daysFromNow = (days: number) => new Date(Date.now() + days * DAY_MS);

  return [
    {
      company: companyId,
      name: "Slack",
      category: "Team communication",
      ownerName: "Maya Chen",
      ownerEmail: "maya@example.com",
      monthlySpend: 1260,
      seatsPurchased: 60,
      activeSeats: 51,
      lastUsedAt: daysAgo(2),
      renewalDate: daysFromNow(45),
      source: "sample",
      notes: "Core messaging tool with upcoming renewal.",
    },
    {
      company: companyId,
      name: "Notion",
      category: "Knowledge base",
      ownerName: "Jordan Lee",
      ownerEmail: "jordan@example.com",
      monthlySpend: 720,
      seatsPurchased: 40,
      activeSeats: 33,
      lastUsedAt: daysAgo(4),
      renewalDate: daysFromNow(118),
      source: "sample",
      notes: "Company wiki and planning docs.",
    },
    {
      company: companyId,
      name: "Figma",
      category: "Design",
      ownerName: "Priya Shah",
      ownerEmail: "priya@example.com",
      monthlySpend: 1080,
      seatsPurchased: 24,
      activeSeats: 22,
      lastUsedAt: daysAgo(1),
      renewalDate: daysFromNow(82),
      source: "sample",
      notes: "Design collaboration for product and marketing.",
    },
    {
      company: companyId,
      name: "Zoom",
      category: "Video conferencing",
      ownerName: "Evan Brooks",
      ownerEmail: "evan@example.com",
      monthlySpend: 480,
      seatsPurchased: 30,
      activeSeats: 28,
      lastUsedAt: daysAgo(3),
      renewalDate: daysFromNow(12),
      source: "sample",
      notes: "Renewal is inside the urgent review window.",
    },
    {
      company: companyId,
      name: "Linear",
      category: "Project management",
      ownerName: "Avery Kim",
      ownerEmail: "avery@example.com",
      monthlySpend: 420,
      seatsPurchased: 35,
      activeSeats: 31,
      lastUsedAt: daysAgo(2),
      renewalDate: daysFromNow(170),
      source: "sample",
      notes: "Engineering issue tracking.",
    },
    {
      company: companyId,
      name: "Asana",
      category: "Project management",
      ownerName: "Sam Rivera",
      ownerEmail: "sam@example.com",
      monthlySpend: 690,
      seatsPurchased: 30,
      activeSeats: 9,
      lastUsedAt: daysAgo(38),
      renewalDate: daysFromNow(52),
      source: "sample",
      notes: "Potential duplicate with Linear and low active usage.",
    },
    {
      company: companyId,
      name: "Salesforce",
      category: "CRM",
      ownerName: "Nora Patel",
      ownerEmail: "nora@example.com",
      monthlySpend: 4200,
      seatsPurchased: 20,
      activeSeats: 8,
      lastUsedAt: daysAgo(6),
      renewalDate: daysFromNow(74),
      source: "sample",
      notes: "High spend account with unused seat exposure.",
    },
    {
      company: companyId,
      name: "HubSpot",
      category: "CRM",
      ownerName: "Leo Martinez",
      ownerEmail: "leo@example.com",
      monthlySpend: 1350,
      seatsPurchased: 12,
      activeSeats: 11,
      lastUsedAt: daysAgo(5),
      renewalDate: daysFromNow(155),
      source: "sample",
      notes: "Marketing CRM usage overlaps partly with Salesforce.",
    },
    {
      company: companyId,
      name: "Miro",
      category: "Collaboration",
      ownerName: "Taylor Green",
      ownerEmail: "taylor@example.com",
      monthlySpend: 540,
      seatsPurchased: 30,
      activeSeats: 0,
      lastUsedAt: daysAgo(142),
      renewalDate: daysFromNow(96),
      source: "sample",
      notes: "Zombie subscription: no active seats and no recent usage.",
    },
    {
      company: companyId,
      name: "Intercom",
      category: "Customer support",
      ownerName: "Casey Nguyen",
      ownerEmail: "casey@example.com",
      monthlySpend: 980,
      seatsPurchased: 10,
      activeSeats: 7,
      lastUsedAt: daysAgo(7),
      renewalDate: daysFromNow(132),
      source: "sample",
      notes: "Support messaging and customer engagement.",
    },
    {
      company: companyId,
      name: "GitHub",
      category: "Developer tools",
      ownerName: "Riley Stone",
      ownerEmail: "riley@example.com",
      monthlySpend: 640,
      seatsPurchased: 40,
      activeSeats: 39,
      lastUsedAt: daysAgo(1),
      renewalDate: daysFromNow(210),
      source: "sample",
      notes: "Engineering source control.",
    },
    {
      company: companyId,
      name: "Datadog",
      category: "Observability",
      ownerName: "Morgan Ali",
      ownerEmail: "morgan@example.com",
      monthlySpend: 2600,
      seatsPurchased: 18,
      activeSeats: 16,
      lastUsedAt: daysAgo(2),
      renewalDate: daysFromNow(43),
      source: "sample",
      notes: "High-spend observability vendor near renewal.",
    },
    {
      company: companyId,
      name: "DocuSign",
      category: "Legal operations",
      ownerName: "Jamie Ross",
      ownerEmail: "jamie@example.com",
      monthlySpend: 310,
      seatsPurchased: 8,
      activeSeats: 4,
      lastUsedAt: daysAgo(27),
      renewalDate: daysFromNow(188),
      source: "sample",
      notes: "Lightly used contract workflow account.",
    },
    {
      company: companyId,
      name: "Canva",
      category: "Design",
      ownerName: "Harper Bell",
      ownerEmail: "harper@example.com",
      monthlySpend: 180,
      seatsPurchased: 15,
      activeSeats: 6,
      lastUsedAt: daysAgo(18),
      renewalDate: daysFromNow(121),
      source: "sample",
      notes: "Marketing design tool with unused seats.",
    },
  ];
}
